-- MySQL Script generated by MySQL Workbench
-- Mon 28 Nov 2016 05:26:15 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema knipster
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `knipster` ;

-- -----------------------------------------------------
-- Schema knipster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knipster` DEFAULT CHARACTER SET utf8 ;
USE `knipster` ;

-- -----------------------------------------------------
-- Table `knipster`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knipster`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(512) NULL,
  `last_name` VARCHAR(512) NULL,
  `gender` VARCHAR(52) NULL,
  `email` VARCHAR(255) NOT NULL,
  `country` VARCHAR(512) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Customer table';


-- -----------------------------------------------------
-- Table `knipster`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knipster`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `customer_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `knipster`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Transactions table';


-- -----------------------------------------------------
-- Table `knipster`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knipster`.`balance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` FLOAT(8) NOT NULL DEFAULT 0,
  `bonus` FLOAT(8) NOT NULL DEFAULT 0,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_balance_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_balance_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `knipster`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
